### ISSUE TITLE
Fail remote rejected

### ISSUE THREAD

**Issue by Ashler** [rtyley/bfg-repo-cleaner#259] opened 2018-01-26 18:00 UTC
Hello!

I'm trying to remove some files from my github repo but when i try to push the changes i get this error: 

! [remote rejected] refs/pull/1/head -> refs/pull/1/head (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/Ashler/ebg-website.git'

Do you know why is this happening? 

Thank you!

**Comment by javabrett** [comment] 2018-01-29 11:59
Duplicate of #36.  You need to contact Github support if you are rewriting history and have pull-requests.

**Comment by Ashler** [comment] 2018-01-31 08:59
Thank you for your help! Now i contact to github and now i can use BFG without problem :)

**Closed** 2018-01-31 09:02 UTC

**Comment by avatar-lavventura** [comment] 2021-09-05 18:26
@Ashler What sould we say GitHub support in order to use BFG?
