### ISSUE TITLE
org.eclipse.jgit.errors.LargeObjectException

### ISSUE THREAD

**Issue by martinthurn-LFT** [rtyley/bfg-repo-cleaner#97] opened 2015-07-15 12:53 UTC
# java -jar bfg-1.12.3.jar --delete-folders FOO

Exception in thread "main" org.eclipse.jgit.errors.LargeObjectException: 6acb82f5b...3d825407 exceeds size limit
	at org.eclipse.jgit.internal.storage.file.LargePackedWholeObject.getCachedBytes(LargePackedWholeObject.java:98)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:202)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator0(CanonicalTreeParser.java:236)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:214)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.createSubtreeIterator(CanonicalTreeParser.java:60)
	at org.eclipse.jgit.treewalk.TreeWalk.enterSubtree(TreeWalk.java:912)
	at org.eclipse.jgit.treewalk.TreeWalk.next(TreeWalk.java:566)
	at com.madgag.git.package$RichTreeWalk$$anon$1.next(package.scala:128)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at com.madgag.git.package$RichTreeWalk$$anon$1.foreach(package.scala:121)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:20)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:295)
	at com.madgag.git.package$RichTreeWalk$$anon$1.to(package.scala:121)
	at scala.collection.TraversableOnce$class.toSet(TraversableOnce.scala:289)
	at com.madgag.git.package$RichTreeWalk$$anon$1.toSet(package.scala:121)
	at com.madgag.git.package$.allBlobsUnder(package.scala:256)
	at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$$anonfun$6.apply(ProtectedObjectCensus.scala:83)
	at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$$anonfun$6.apply(ProtectedObjectCensus.scala:83)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.madgag.git.bfg.cleaner.protection.ProtectedObjectCensus$.apply(ProtectedObjectCensus.scala:83)
	at com.madgag.git.bfg.cli.CLIConfig.objectProtection$lzycompute(CLIConfig.scala:141)
	at com.madgag.git.bfg.cli.CLIConfig.objectProtection(CLIConfig.scala:141)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:57)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:34)
	at scala.Option.map(Option.scala:146)
	at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:33)
	at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
	at com.madgag.git.bfg.cli.Main.main(Main.scala)

**Comment by martinthurn-LFT** [comment] 2015-08-26 12:20
Here's another one:

java -jar /usr/local/src/bfg-1.12.4.jar --delete-files input_file_list.txt Mirror.git
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Using repo : /home/martin/Mirror.git

Found 1259 objects to protect
Found 10 commit-pointing refs : HEAD, refs/heads/installer-testing-branch, refs/heads/master, ...

Protected commits
-----------------

These are your protected commits, and so their contents will NOT be altered:

 * commit 1b329a99 (protected by 'HEAD')

Cleaning
--------

Found 1841 commits
Cleaning commits:        10% ( 185/1841)Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectException: 6acb82f5bda91325f37aa7b51d6506963d825407 exceeds size limit
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:60)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner.apply(ObjectIdCleaner.scala:75)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:112)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1$$anonfun$apply$mcV$sp$3.apply(RepoRewriter.scala:111)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply$mcV$sp(RepoRewriter.scala:110)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:103)
	at com.madgag.git.bfg.cleaner.RepoRewriter$$anonfun$clean$1$1.apply(RepoRewriter.scala:103)
	at com.madgag.git.bfg.Timing$.measureTask(timing.scala:39)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.clean$1(RepoRewriter.scala:103)
	at com.madgag.git.bfg.cleaner.RepoRewriter$.rewrite(RepoRewriter.scala:144)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:59)
	at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:34)
	at scala.Option.map(Option.scala:146)
	at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:33)
	at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
	at com.madgag.git.bfg.cli.Main.main(Main.scala)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectException: 6acb82f5bda91325f37aa7b51d6506963d825407 exceeds size limit
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:60)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$uncachedClean$1.apply(ObjectIdCleaner.scala:87)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$uncachedClean$1.apply(ObjectIdCleaner.scala:85)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:74)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 28 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectException: 6acb82f5bda91325f37aa7b51d6506963d825407 exceeds size limit
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:60)
	at com.madgag.git.bfg.model.CommitArcs.cleanWith(Commit.scala:57)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$1.apply(ObjectIdCleaner.scala:102)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$1.apply(ObjectIdCleaner.scala:98)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:74)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 39 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectException: 6acb82f5bda91325f37aa7b51d6506963d825407 exceeds size limit
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:60)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4$$anonfun$5.apply(ObjectIdCleaner.scala:126)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4$$anonfun$5.apply(ObjectIdCleaner.scala:125)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4.apply(ObjectIdCleaner.scala:125)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4.apply(ObjectIdCleaner.scala:118)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:74)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 51 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectException: 6acb82f5bda91325f37aa7b51d6506963d825407 exceeds size limit
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:60)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4$$anonfun$5.apply(ObjectIdCleaner.scala:126)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4$$anonfun$5.apply(ObjectIdCleaner.scala:125)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4.apply(ObjectIdCleaner.scala:125)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4.apply(ObjectIdCleaner.scala:118)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:74)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 70 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: org.eclipse.jgit.errors.LargeObjectException: 6acb82f5bda91325f37aa7b51d6506963d825407 exceeds size limit
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.madgag.git.bfg.MemoUtil$$anonfun$concurrentCleanerMemo$1$$anon$1.apply(memo.scala:60)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4$$anonfun$5.apply(ObjectIdCleaner.scala:126)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4$$anonfun$5.apply(ObjectIdCleaner.scala:125)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4.apply(ObjectIdCleaner.scala:125)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4.apply(ObjectIdCleaner.scala:118)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:74)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 90 more
Caused by: org.eclipse.jgit.errors.LargeObjectException: 6acb82f5bda91325f37aa7b51d6506963d825407 exceeds size limit
	at org.eclipse.jgit.internal.storage.file.LargePackedWholeObject.getCachedBytes(LargePackedWholeObject.java:98)
	at org.eclipse.jgit.treewalk.CanonicalTreeParser.reset(CanonicalTreeParser.java:202)
	at com.madgag.git.bfg.model.Tree$.entriesFor(Tree.scala:39)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4.apply(ObjectIdCleaner.scala:119)
	at com.madgag.git.bfg.cleaner.ObjectIdCleaner$$anonfun$4.apply(ObjectIdCleaner.scala:118)
	at com.madgag.git.bfg.MemoUtil$$anon$3.load(memo.scala:74)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 108 more

**Comment by rtyley** [comment] 2015-08-26 12:23
Can you tell me what kind of object `6acb82f5bda91325f37aa7b51d6506963d825407` is?

Use this command:

```
$ git cat-file -t 6acb82f5bda91325f37aa7b51d6506963d825407
```

**Comment by martinthurn-LFT** [comment] 2015-08-26 12:42
It just says 'tree'



 - - Martin Thurn

     571-528-6531



________________________________

**Comment by rtyley** [comment] 2015-08-26 12:45
Sounds like a very big folder. Could you give me the output of these two commands:

```
git cat-file -s 6acb82f5bda91325f37aa7b51d6506963d825407
```

...should just return the byte size of the object. And also...

```
git cat-file -s 6acb82f5bda91325f37aa7b51d6506963d825407
```

...probably best to paste that into a gist rather directly into this issue, it could be very big.

**Comment by rtyley** [comment] 2015-08-26 12:48
Copy and paste error there - should be `-p` on the second one.

**Comment by martinthurn-LFT** [comment] 2015-08-26 12:52
The size is

4905420


The file list shows 109,059 files like this:


100644 blob f5ce78c885a36135e8ae38d37b8a408cfb4e7c62    FOO_0700145.json

100644 blob ee7350077abd9292cd1af288c0c0afbd6a30f396    FOO_0700146.json

100644 blob b0e23c97d7eb782db421bbf467ab84d54919857f    FOO_0700147.json

(The folder containing these files one of the things I wanted to delete using BFG 8-)

BTW thank you for looking at this!



 - - Martin Thurn

     571-528-6531



________________________________

**Comment by rtyley** [comment] 2015-08-26 13:07
> The size is
> 
> 4905420

You've got a very big folder there. Folders are represented by objects called 'trees' in Git- each line contains one entry in the folder. The JGit library used by the BFG does not expect to have to stream these tree objects into memory - it expects to be able to load the full object into memory before using it, but also has a configured maximum size for such objects, which defaults to 1MB.

Your folder is 4.9MB, _just to represent the folder entries_ - not the actual files in the folder! So you need to add the `--massive-non-file-objects-sized-up-to` flag. If you run the BFG without arguments, it gives you help on this option - see also #20.

**Comment by martinthurn-LFT** [comment] 2015-08-26 13:36
THANK YOU!  I added that argument and the above error is not happening.

**Comment by vahtis** [comment] 2016-04-21 07:21
Hi
I have this issue and I have tried solutions suggested here and also in #20.

`java -jar bfg-1.12.12.jar --delete-files libxerces-c-3.1.so --massive-non-file-objects-sized-up-to 25M laskenta.git`

Exception in thread "main" org.eclipse.jgit.errors.LargeObjectException$OutOfMemory: Out of memory loading 7de3508c3d4c4e406a02e689cf1e69b3697501de
        at org.eclipse.jgit.lib.ObjectLoader.getCachedBytes(ObjectLoader.java:200)
        at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:909)
        at org.eclipse.jgit.revwalk.RevWalk.parseNew(RevWalk.java:873)
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
        at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
        at com.madgag.git.package$RichObjectId.asRevCommit(package.scala:229)
        at com.madgag.git.bfg.GitUtil$$anonfun$hasBeenProcessedByBFGBefore$3.apply(GitUtil.scala:65)
        at com.madgag.git.bfg.GitUtil$$anonfun$hasBeenProcessedByBFGBefore$3.apply(GitUtil.scala:65)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at com.madgag.git.bfg.GitUtil$.hasBeenProcessedByBFGBefore(GitUtil.scala:65)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:47)
        at com.madgag.git.bfg.cli.Main$$anonfun$1.apply(Main.scala:34)
        at scala.Option.map(Option.scala:146)
        at com.madgag.git.bfg.cli.Main$.delayedEndpoint$com$madgag$git$bfg$cli$Main$1(Main.scala:33)
        at com.madgag.git.bfg.cli.Main$delayedInit$body.apply(Main.scala:27)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.madgag.git.bfg.cli.Main$.main(Main.scala:27)
        at com.madgag.git.bfg.cli.Main.main(Main.scala)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.eclipse.jgit.lib.ObjectLoader.getCachedBytes(ObjectLoader.java:198)
        ... 27 more

Stats of commit 7de3508c3d4c4e406a02e689cf1e69b3697501de
$ cd laskenta.git; git cat-file -s 7de3508c3d4c4e406a02e689cf1e69b3697501de
1442224

$ git cat-file -p 7de3508c3d4c4e406a02e689cf1e69b3697501de
tree b041022b4134198979ba9e4e1d9e14b7963de459
parent f13e068db34ce9c123da96096af1732fe9fbbf93
author cvs2git <> 1323678941 +0000
committer cvs2git <> 1323678941 +0000

This commit was manufactured by cvs2svn to create tag 'rel_110315'.

Sprout from master 2011-12-12 08:35:40 UTC tbvvahte '0000110315'
Delete:
    Boost/1_38_0/boost/accumulators/accumulators.hpp
    Boost/1_38_0/boost/accumulators/accumulators_fwd.hpp
    Boost/1_38_0/boost/accumulators/framework/accumulator_base.hpp
... plus 27000 rows more

Any new ideas to test?

**Comment by javabrett** [comment] 2016-04-21 09:09
Your error is different, you have an `OutOfMemoryError`.  Try running `java` with `-Xms1G -Xmx4G` options or similar/larger numbers to suit your hardware.

**Comment by vahtis** [comment] 2016-04-21 11:23
Thx javabrett. I had to switch to 64bit java and then I was able to use -Xms1G -Xmx4G options.

**Comment by javabrett** [comment] 2016-04-21 11:50
If your issue is resolved then you might want to close this issue.

**Comment by vahtis** [comment] 2016-04-21 12:32
I cannot close, but maybe @martinthurn-LFT could do it?

**Closed** 2016-04-21 12:50 UTC
