### ISSUE TITLE
political messaging

### ISSUE THREAD

**Issue by jonzim** [rtyley/bfg-repo-cleaner#223] opened 2017-07-01 15:32 UTC
While i appreciate that you have strong opinions, it's not really appropriate for every environment... mine included where we try to remain a-political.   Plus it's irrelevant in most of the world.   I'll have to either download an older version or clone the source on my box to remove it.

Politicize your website if you want, but in the code it's probably inappropriate.

**Comment by draeath** [comment] 2017-07-07 18:16
I have to say I agree, even if I strongly agree with your message. It doesn't seem like an appropriate place to put it.

**Comment by draeath** [comment] 2017-07-07 18:17
Also a duplicate of #205

**Comment by humford** [comment] 2017-07-17 17:24
@rtyley doing triage and it seems this issue can pretty easily just be closed since it's a duplicate of the previously resolved #205 and #206

**Comment by lyda** [comment] 2017-09-28 15:13
Just a note, as an American overseas I really appreciate the message. Will be recommending BFG to friends. Making git repos more compact makes the world a better place and so does the ACLU. Thanks.

**Comment by zingmars** [comment] 2017-11-03 14:19
I'm with OP on this one. It's bad enough that I have to hear about the mess that is Trump every time I open a western news site, but having to see it when I'm working is just annoying. 

And really? A link to the Guardian? That site basically yellow journalism.

**Closed** 2017-11-03 14:21 UTC
