### ISSUE TITLE
strange message in output

### ISSUE THREAD

**Issue by slang800** [rtyley/bfg-repo-cleaner#266] opened 2018-03-14 22:50 UTC
When I run the tool, it operates correctly, but at the end of the output I get this message:

```
--
You can rewrite history in Git - don't let Trump do it for real!
Trump's administration has lied consistently, to make people give up on ever
being told the truth. Don't give up: https://www.theguardian.com/us-news/trump-administration
--
```

...Which is unexpected and weird. I get it every time I use the tool, so it should be easy to reproduce. It's not clear why it's there or how to disable it, since it has nothing to do with bfg. Is this some kind of paid ad for The Guardian?

**Comment by carefulnow1** [comment] 2018-03-25 22:20
This certainly is strange. I've used this tool quite a lot, and it seems the source file is here: https://github.com/rtyley/bfg-repo-cleaner/blob/8a452b9cfe0fb6bf850da53a539ea1484b8f8587/bfg/src/main/scala/com/madgag/git/bfg/cli/stoptrump/package.scala

**Comment by lsh-0** [comment] 2018-04-04 06:04
yeah, what the hell?? leave North American politics out of your software, please.

**Comment by oganm** [comment] 2018-04-23 22:05
Duplicate of https://github.com/rtyley/bfg-repo-cleaner/issues/205 and https://github.com/rtyley/bfg-repo-cleaner/issues/206

**Comment by honkskillet** [comment] 2018-05-04 19:59
This needs to be removed.  Get the dumb politics out of a software tool and grow up.

**Comment by oganm** [comment] 2018-05-04 22:45
https://github.com/Tatsh/bfg-repo-cleaner/releases is an older version but should still work if you wish for a non-political version. remember that this is free software with well documented build instructions.

**Closed** 2018-05-05 07:36 UTC
